### ISSUE TITLE
Can't build Metamod

### ISSUE THREAD

**Issue by LowArte** [alliedmodders/metamod-source#117]
Trying to build metamod, but get this error:
```
python ../configure.py
Checking CC compiler (vendor test msvc)... ['C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64_x86\\cl.exe', 'test.c', '-o', 'test-c.exe', '-nologo', '-showIncludes']
found msvc version 1900, x86
Checking CXX compiler (vendor test msvc)... ['C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64_x86\\cl.exe', 'test.cpp', '-o', 'test-cxx.exe', '-nologo', '-showIncludes']
found msvc version 1900, x86
Checking CC compiler (vendor test msvc)... ['C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe', 'test.c', '-o', 'test-c.exe', '-nologo', '-showIncludes']
found msvc version 1900, x86_64
Checking CXX compiler (vendor test msvc)... ['C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe', 'test.cpp', '-o', 'test-cxx.exe', '-nologo', '-showIncludes']
found msvc version 1900, x86_64
Traceback (most recent call last):
  File "C:\Users\LowArt\AppData\Roaming\Python\Python311\site-packages\ambuild-2.0-py3.11.egg\ambuild2\frontend\v2_2\prep.py", line 143, in Configure
    if not cm.generate(options.generator):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LowArt\AppData\Roaming\Python\Python311\site-packages\ambuild-2.0-py3.11.egg\ambuild2\frontend\context_manager.py", line 93, in generate
    self.parseBuildScripts()
  File "C:\Users\LowArt\AppData\Roaming\Python\Python311\site-packages\ambuild-2.0-py3.11.egg\ambuild2\frontend\v2_2\context_manager.py", line 50, in parseBuildScripts
    self.execContext(cx)
  File "C:\Users\LowArt\AppData\Roaming\Python\Python311\site-packages\ambuild-2.0-py3.11.egg\ambuild2\frontend\v2_2\context_manager.py", line 148, in execContext
    exec(code, scriptGlobals)
  File "D:\work\other\metamod-source\AMBuildScript", line 546, in <module>
    MMS.detectSDKs()
  File "D:\work\other\metamod-source\AMBuildScript", line 181, in detectSDKs
    raise Exception('No SDKs were found, nothing to build.')
Exception: No SDKs were found, nothing to build.
Configure failed: No SDKs were found, nothing to build.
```

What i'm doing wrong ?

**Comment by psychonic** [comment]
This looks to be a configuration issue with your SDK paths and/or environment variables. For assistance with configuration issue, please use the AlliedModders [forum](forums.alliedmods.net/) or [Discord](https://discord.gg/HUc67zN).

This section is for reporting bugs or requesting features in MM:S.
