### ISSUE TITLE
Linux BMS Metamod crash on startup

### ISSUE THREAD

**Issue by hltv** [alliedmodders/metamod-source#45]
Greetings,

Since the last bms update "https://steamcommunity.com/games/362890/announcements/detail/1669024110904289413" srcds crash with metamod.

In the first bms update(early 29.04) the dedicated.so was missing.
We could start a dedicated via copy and rename the dedicated_srv.so

Another update, some hours later, ships the dedicated.so file but the server crash with "Unable to load interface VCvarQuery001 from engine.so, requested from EXE.".
I also copy and rename the dedicated_srv.so to dedicated.so and the server starts and runs stable.

There are some others problems right now, like empty public server list - so another update will hit very soon i think.

anyway, we can play via hlsw or the "history tab".

I do not know if that makes sense now to begin debug right now. or waiting for the next update.
I was able to join with the client (second update) on the server with the first update. I think nothing big will be changed in the upcoming update. But it would be nice – so we can start testing our sourcemod plugins on the new version.

Trace via a clean srcds install + mms:1.11 1103 – no other plugins:

Thread 1 "srcds_linux" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf7b9aec0 (LWP 14911)]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xf6ae5e63 in ConVarNetworkChangeCallback(IConVar*, char const*, float) () from /bmsclean3/bms/bin/engine_srv.so
#2  0xf76f8fa3 in CCvar::CallGlobalChangeCallbacks(ConVar*, char const*, float) () from bin/libvstdlib_srv.so
#3  0xf3b5c22e in ConVar::ChangeStringValue(char const*, float) () from /bmsclean3/bms/bms/addons/metamod/bin/metamod.2.bms.so
#4  0xf3b5c053 in ConVar::InternalSetValue(char const*) () from /bmsclean3/bms/bms/addons/metamod/bin/metamod.2.bms.so
#5  0xf3b4d787 in BaseProvider::SetConVarString(ConVar*, char const*) () from /bmsclean3/bms/bms/addons/metamod/bin/metamod.2.bms.so
#6  0x08862b20 in ?? ()
#7  0x61477265 in ?? ()
#8  0x6c43656d in ?? ()
#9  0x746e6569 in ?? ()
#10 0x34303073 in ?? ()
#11 0xf3b80100 in mm_fatal_logfile () from /bmsclean3/bms/bms/addons/metamod/bin/server.so
#12 0x76726553 in ?? ()
#13 0x61477265 in ?? ()
#14 0x4c44656d in ?? ()
#15 0x3031304c in ?? ()
#16 0xf4a20100 in CDllDemandLoader::~CDllDemandLoader() () from /bmsclean3/bms/bms/bin/server_srv.so
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

**Comment by psychonic** [comment]
I believe that this is fixed now. (However an updated SourceMod build will be needed as well if you are using that).

Can you confirm with build 1105 from http://sourcemm.net/downloads.php?branch=dev (without SourceMod).
