### ISSUE TITLE
Crash on server shutdown

### ISSUE THREAD

**Issue by Accelerator74** [alliedmodders/metamod-source#86]
Sometimes when the server shutdown, I get a crash. The server is restarted with the `_restart` command. MetaMod 1.11.1144

Backtrace:
```
#0  0xf00df78b in SourceHook::CPageAlloc::Free(void*) () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
#1  0xf00e0560 in SourceHook::Impl::GenContext::~GenContext() () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
#2  0xf00e635f in SourceHook::Impl::CHookManagerAutoGen::~CHookManagerAutoGen() () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
#3  0xf7cfbdf5 in __cxa_finalize () from /lib32/libc.so.6
#4  0xf00d1b03 in __do_global_dtors_aux () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
#5  0xf7ef0c3c in ?? () from /lib/ld-linux.so.2
#6  0xf7ef1643 in ?? () from /lib/ld-linux.so.2
#7  0xf7dff45c in _dl_catch_exception () from /lib32/libc.so.6
#8  0xf7dff500 in _dl_catch_error () from /lib32/libc.so.6
#9  0xf7ecaa71 in ?? () from /lib32/libdl.so.2
#10 0xf7eca411 in dlclose () from /lib32/libdl.so.2
#11 0xf6b1a4ac in mm_UnloadLibrary(void*) () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/server.so
#12 0xf6b1851f in mm_UnloadMetamodLibrary() () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/server.so
#13 0xf6b19de9 in ServerPlugin::Unload() () from /home/user/l4d2_coop/left4dead2/addons/metamod/bin/server.so
#14 0xf720811c in CPlugin::Unload() () from /home/user/l4d2_coop/bin/engine_srv.so
#15 0xf72088b9 in CServerPlugin::UnloadPlugins() () from /home/user/l4d2_coop/bin/engine_srv.so
#16 0xf71fb6d5 in SV_ShutdownGameDLL() () from /home/user/l4d2_coop/bin/engine_srv.so
#17 0xf7215142 in CModAppSystemGroup::Main() () from /home/user/l4d2_coop/bin/engine_srv.so
#18 0xf726a028 in CAppSystemGroup::Run() () from /home/user/l4d2_coop/bin/engine_srv.so
#19 0xf7215faf in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /home/user/l4d2_coop/bin/engine_srv.so
#20 0xf74ba845 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#21 0xf74db498 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#22 0xf74db498 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#23 0xf7485197 in main () from bin/dedicated_srv.so
#24 0x08048722 in main ()
```

**Comment by asherkin** [comment]
What is the crash reason? Do you have a coredump you can share?

I don't think that stack trace indicates an issue in MM:S, it's possibly just the memory allocator detecting heap corruption.

**Comment by Accelerator74** [comment]
Unfortunately there is no access to the dump itself. There is only a stacktrace.

**Comment by Accelerator74** [comment]
Some people argue that this is a problem with Dhooks. When there are some active hooks through dhooks, and try to shut down the server, it will crash.

Well it looks like this is not a metamod problem.

**Comment by peace-maker** [comment]
This might already be fixed by https://github.com/peace-maker/DHooks2/commit/314f9264e88937145a84001d9877015bd113278c which didn't make its way into a release yet. Can't tell from the stacktrace only.
